### ISSUE TITLE
Not appear OTC deals for HDXb

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/snakewatch#13]
Only appear the wants to buy/sell HDXb

But not appear the deals that fill these orders

**Comment by myParakeet** [comment]
Appears resolved. 
![image](https://github.com/galacticcouncil/snakewatch/assets/1441132/89e3a136-c1e8-4a36-ad4a-a2e8a1c4fb08)

**Comment by joseJRJR** [comment]
Not really, that are the swaps from the xyk pool of HDXb<> HDX

When someone fill a partial or complete otc orde, appear otc at the end of the msg

Example: 
![Screenshot_20240108_004917_Discord](https://github.com/galacticcouncil/snakewatch/assets/123791232/063ecb1e-18a2-43ad-8fba-833b14d7e124)

**Comment by myParakeet** [comment]
My mistake. Thanks.
