### ISSUE TITLE
Discord - hyperlink to subscan

### ISSUE THREAD

**Issue by myParakeet** [galacticcouncil/snakewatch#15]
Can the three character "short" form of the address or the emoji be converted to a clickable hyperlink ?  

Discord users would be able to click the three characters after the emoji (or the emoji itself) and be taken to: 
"https://hydradx.subscan.io/account/[address]"

Searching suggests this is possible with bots and embeds using a format of [text](url).

Maybe this might work for the url? 
const subscanURL = `https://hydradx.subscan.io/account/${address.toString()}`;

Or something like (this line is almost certainly incorrect:
export const formatAccount = (address, whale, icon = `🐍`) => (whale ? '🐋' : icon) + `[${short(address)}](https://hydradx.subscan.io/account/${address.toString()})`;

<3 <3 <3 with love from discord Watchooooors! <3 <3 <3

**Comment by mrq1911** [comment]
fixed
