### ISSUE TITLE
Not appear the evm swaps from external assets

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/snakewatch#21]
Thanks to the update, now.i can see the evm txs for a swap like dot > hdx, but none of the swaps from.the screenshot appear on omniwatch 
![Screenshot_368](https://github.com/galacticcouncil/snakewatch/assets/123791232/2119ff6a-9d2a-409c-a1b2-f66d881eb0dc)

**Comment by joseJRJR** [comment]
The tx link for the pink > stink trade

https://explorer.evm.hydration.cloud/tx/0xd967326e2760f5435a2e0fb206d6d05a5d951e9169d013ba1540897f2843b0c4

https://hydradx.subscan.io/tx/0xd967326e2760f5435a2e0fb206d6d05a5d951e9169d013ba1540897f2843b0c4

**Comment by mrq1911** [comment]
nice, there was a separate issue when using router
